version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:

    # Primary container image where all commands run
    docker:
      - image: cimg/node:18.15.0

    # Service container image available at `host: localhost`
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_DB: circle-test
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
    environment:
      NODE_ENV: test
      POSTGRES_USER: circleci
      POSTGRES_DB: circleci
    parallelism: 5
    steps:
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - checkout
      - run:
          name: Check Node Version
          command: node --version
      - run:
          name: Check test folder file
          working_directory: ./src/tests
          command: ls -a
      - node/install-packages:
          app-dir: ./
          cache-path: ./node_modules
          override-ci-command: yarn install
      - run:
          command: npx prisma migrate dev --name init
          working_directory: ./
          name: Prisma Generate
      - run:
          command: yarn test
          working_directory: ./
          name: Unit Testing
      - run:
          command: yarn test:e2e
          working_directory: ./
      # - store_test_results:
      #     path: ./edison-api/coverage
      # - store_artifacts:
      #     path: ./edison-api/coverage
workflows:
  build-and-test:
    jobs:
      - build-and-test
